### ISSUE TITLE
Create repository tags for 0.6.1 and 0.6.2

### ISSUE THREAD

**Issue by koobs** [racker/rackspace-monitoring#44]
Quite handy to have :)

**Comment by mburns** [comment]
![woops](https://cloud.githubusercontent.com/assets/5170/17350025/ce5903a8-58d7-11e6-8a45-a88d7b6773e6.jpg)

For posterity. 
* https://github.com/racker/rackspace-monitoring/releases/tag/v0.6.1
* https://github.com/racker/rackspace-monitoring/releases/tag/v0.6.2
