### ISSUE TITLE
Libcloud 0.15.0 does not honor proxy settings

### ISSUE THREAD

**Issue by kstev** [racker/rackspace-monitoring#50]
The latest upgrade took apache-libcloud requirements from 0.18.0 to 0.15.0. Unfortunately, apache-libcloud acquired support for http proxy settings in 0.16.0 according to [the release notes](https://libcloud.apache.org/blog/tags/release%20announcement.html)

This being the case, rackspace-monitoring no longer works in environments behind a proxy.

**Comment by dimtruck** [comment]
#51 merged.
